import type { Metadata } from 'next';
import { Anton, Manrope, Syne, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { Providers } from '@/components/providers';
import { cn } from '@/lib/cn';
import SmoothScroll from '@/components/smooth-scroll';

export const anton = Anton({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-anton',
});

export const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
});

export const syne = Syne({
  subsets: ['latin'],
  variable: '--font-syne',
});

export const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <body
        className={cn(
          anton.variable,
          manrope.variable,
          syne.variable,
          jetbrainsMono.variable,
          'min-h-screen flex flex-col font-sans'
        )}
      >
        <Providers>
          <SmoothScroll>{children}</SmoothScroll>
        </Providers>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
