import type { Metadata } from 'next';
import {
  Geist_Mono,
  Inter,
  Outfit,
  Anton,
  Manrope,
  Syne,
  JetBrains_Mono,
} from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { Providers } from '@/components/providers';
import { cn } from '@/lib/cn';
import SmoothScroll from '@/components/smooth-scroll';

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
});

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const anton = Anton({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-anton',
});

export const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
});

export const syne = Syne({
  subsets: ['latin'],
  variable: '--font-syne',
});

export const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} ${outfit.variable} h-full antialiased`}
    >
      <body
        className={cn(
          anton.variable,
          manrope.variable,
          syne.variable,
          jetbrainsMono.variable,
          'min-h-full flex flex-col font-sans'
        )}
      >
        <Providers>
          <SmoothScroll>{children}</SmoothScroll>
        </Providers>
        <Toaster
          position="bottom-right"
          toastOptions={{
            style: {
              background: 'hsl(var(--popover))',
              color: 'hsl(var(--popover-foreground))',
              border: '1px solid hsl(var(--border))',
              borderRadius: 'var(--radius)',
              fontFamily: 'var(--font-mono)',
              letterSpacing: '0.04em',
              textTransform: 'uppercase',
              fontSize: '12px',
            },
          }}
        />
      </body>
    </html>
  );
}
